#!/usr/bin/env bash

set -euo pipefail

readonly executable=SWBWA
readonly layout_header=swbwa_cpe_layout.h

write_layout_header()
{
    local text_start=$1
    local text_size=$2
    local data_start=$3
    local data_size=$4

    cat > "${layout_header}" <<EOF
#ifndef SWBWA_CPE_LAYOUT_H
#define SWBWA_CPE_LAYOUT_H

/* Generated by build_cross.sh. */
#define SWBWA_CPE_TEXT_START_ADDRESS ${text_start}UL
#define SWBWA_CPE_TEXT_SEGMENT_BYTES ${text_size}UL
#define SWBWA_CPE_DATA_START_ADDRESS ${data_start}UL
#define SWBWA_CPE_DATA_SEGMENT_BYTES ${data_size}UL

#endif /* SWBWA_CPE_LAYOUT_H */
EOF
}

build_swbwa()
{
    make clean
    make -j "$@"
}

write_layout_header 123 123 123 123
build_swbwa "$@"

text_start=$(swreadelf -l "./${executable}" | sed -n '9p' | awk '{print $3}')
text_size=$(swreadelf -l "./${executable}" | sed -n '10p' | awk '{print $1}')
data_start=$(swreadelf -l "./${executable}" | sed -n '11p' | awk '{print $3}')
data_size=$(swreadelf -l "./${executable}" | sed -n '12p' | awk '{print $2}')

write_layout_header "${text_start}" "${text_size}" "${data_start}" "${data_size}"
build_swbwa "$@"

python3 xlink.py "${executable}"
swreadelf -r "${executable}" > "${executable}.relocations"
python3 get_tls.py "${executable}.relocations"
