#ifndef SWBWA_CONFIG_H
#define SWBWA_CONFIG_H

/*
 * Central build-time configuration shared by MPE and CPE code.
 *
 * Prefer the Makefile interface instead of defining these values directly:
 *
 *   make EXEC_MODE=single CPE_ALLOCATOR=system
 *   make EXEC_MODE=cgs CPE_ALLOCATOR=system
 *   make EXEC_MODE=cgs_cross CPE_ALLOCATOR=pool
 *   make USE_MPI=1 MPI_INPUT_MODE=dynamic OUTPUT_MODE=split
 *   make USE_MPI=1 MPI_INPUT_MODE=dynamic MPI_EXACT_READ_INDEX=1
 *   make HOST_MALLOC_WRAPPER=1 HOST_MALLOC_STATS=1
 */

#ifndef SWBWA_USE_MPI
#define SWBWA_USE_MPI 0
#endif

#if SWBWA_USE_MPI != 0 && SWBWA_USE_MPI != 1
#error "SWBWA_USE_MPI must be 0 or 1"
#endif

#define SWBWA_MPI_INPUT_STATIC  1
#define SWBWA_MPI_INPUT_DYNAMIC 2

#if SWBWA_USE_MPI
#ifndef SWBWA_MPI_INPUT_MODE
#define SWBWA_MPI_INPUT_MODE SWBWA_MPI_INPUT_DYNAMIC
#endif

#if SWBWA_MPI_INPUT_MODE != SWBWA_MPI_INPUT_STATIC && \
    SWBWA_MPI_INPUT_MODE != SWBWA_MPI_INPUT_DYNAMIC
#error "invalid SWBWA_MPI_INPUT_MODE"
#endif

#ifndef SWBWA_MPI_EXACT_READ_INDEX
#define SWBWA_MPI_EXACT_READ_INDEX 0
#endif

#if SWBWA_MPI_EXACT_READ_INDEX != 0 && SWBWA_MPI_EXACT_READ_INDEX != 1
#error "SWBWA_MPI_EXACT_READ_INDEX must be 0 or 1"
#endif

#define SWBWA_OUTPUT_SPLIT             1
#define SWBWA_OUTPUT_SINGLE_UNORDERED  2

#ifndef SWBWA_OUTPUT_MODE
#define SWBWA_OUTPUT_MODE SWBWA_OUTPUT_SPLIT
#endif

#if SWBWA_OUTPUT_MODE != SWBWA_OUTPUT_SPLIT && \
    SWBWA_OUTPUT_MODE != SWBWA_OUTPUT_SINGLE_UNORDERED
#error "invalid SWBWA_OUTPUT_MODE"
#endif
#endif /* SWBWA_USE_MPI */

#define SWBWA_EXEC_SINGLE_CG  1
#define SWBWA_EXEC_CGS        2
#define SWBWA_EXEC_CGS_CROSS  3

#ifndef SWBWA_EXEC_MODE
#define SWBWA_EXEC_MODE SWBWA_EXEC_CGS_CROSS
#endif

#if SWBWA_EXEC_MODE != SWBWA_EXEC_SINGLE_CG && \
    SWBWA_EXEC_MODE != SWBWA_EXEC_CGS && \
    SWBWA_EXEC_MODE != SWBWA_EXEC_CGS_CROSS
#error "invalid SWBWA_EXEC_MODE"
#endif

#if SWBWA_EXEC_MODE == SWBWA_EXEC_SINGLE_CG
#define SWBWA_USE_CGS 0
#define SWBWA_CPE_COUNT 64
#define SWBWA_CG_COUNT 1
#else
#define SWBWA_USE_CGS 1
#define SWBWA_CPE_COUNT 384
#define SWBWA_CG_COUNT 6
#endif

#if SWBWA_EXEC_MODE == SWBWA_EXEC_CGS_CROSS
#define SWBWA_USE_CROSS_SEGMENT 1
#else
#define SWBWA_USE_CROSS_SEGMENT 0
#endif

#define SWBWA_CPE_ALLOC_SYSTEM 1
#define SWBWA_CPE_ALLOC_POOL   2

#ifndef SWBWA_CPE_ALLOC_MODE
#define SWBWA_CPE_ALLOC_MODE SWBWA_CPE_ALLOC_SYSTEM
#endif

#if SWBWA_CPE_ALLOC_MODE != SWBWA_CPE_ALLOC_SYSTEM && \
    SWBWA_CPE_ALLOC_MODE != SWBWA_CPE_ALLOC_POOL
#error "invalid SWBWA_CPE_ALLOC_MODE"
#endif

#ifndef SWBWA_ENABLE_HOST_MALLOC_WRAPPER
#define SWBWA_ENABLE_HOST_MALLOC_WRAPPER 1
#endif

#ifndef SWBWA_ENABLE_HOST_MALLOC_STATS
#define SWBWA_ENABLE_HOST_MALLOC_STATS 0
#endif

#if SWBWA_ENABLE_HOST_MALLOC_STATS != 0 && \
    SWBWA_ENABLE_HOST_MALLOC_STATS != 1
#error "SWBWA_ENABLE_HOST_MALLOC_STATS must be 0 or 1"
#endif

#if SWBWA_ENABLE_HOST_MALLOC_STATS && !SWBWA_ENABLE_HOST_MALLOC_WRAPPER
#error "host malloc statistics require the host malloc wrapper"
#endif

#ifndef SWBWA_ENABLE_CPE_MALLOC_WRAPPER
#if SWBWA_CPE_ALLOC_MODE == SWBWA_CPE_ALLOC_POOL
#define SWBWA_ENABLE_CPE_MALLOC_WRAPPER 1
#else
#define SWBWA_ENABLE_CPE_MALLOC_WRAPPER 0
#endif
#endif

/* Internal CPE tuning. These are intentionally not Makefile-level modes. */
#define SWBWA_ENABLE_DYNAMIC_SCHEDULING 1
#define SWBWA_ENABLE_CPE_PREFETCH       1
#define SWBWA_ENABLE_TWO_PASS_BATCH     0
#define SWBWA_ENABLE_WORKER2_LDM        0
#define SWBWA_ENABLE_FLOAT16_VECTOR     0
#define SWBWA_ENABLE_PACKED_INT8        0
#define SWBWA_ENABLE_SWLU               0

#define SWBWA_READS_PER_DYNAMIC_TASK    1
#define SWBWA_MAX_TASKS_PER_CPE          (50 << 10)
#define SWBWA_CPE_PREFETCH_DISTANCE      8
#define SWBWA_TWO_PASS_BATCH_SIZE        8
#define SWBWA_PIPELINE_QUEUE_CAPACITY    4
#define SWBWA_PIPELINE_BUFFER_COUNT      (SWBWA_PIPELINE_QUEUE_CAPACITY + 1)

#if SWBWA_USE_MPI && \
    SWBWA_MPI_INPUT_MODE == SWBWA_MPI_INPUT_DYNAMIC
#define SWBWA_PIPELINE_INPUT_QUEUE_CAPACITY 1
#else
#define SWBWA_PIPELINE_INPUT_QUEUE_CAPACITY SWBWA_PIPELINE_QUEUE_CAPACITY
#endif

#ifndef SWBWA_CPE_POOL_BYTES_PER_CPE
#define SWBWA_CPE_POOL_BYTES_PER_CPE (24LL << 20)
#endif

#ifndef SWBWA_CPE_FORMAT_BUFFER_BYTES
#define SWBWA_CPE_FORMAT_BUFFER_BYTES (512LL << 20)
#endif

#ifndef SWBWA_OUTPUT_BUFFER_BYTES
#define SWBWA_OUTPUT_BUFFER_BYTES (8LL << 20)
#endif

#define SWBWA_SAM_RECORD_SLACK_BYTES 10
#define SWBWA_MAX_READS_PER_BATCH    2000000

#define SWBWA_CPE_POOL_TOTAL_BYTES \
    (1LL * SWBWA_CPE_COUNT * SWBWA_CPE_POOL_BYTES_PER_CPE)

#endif /* SWBWA_CONFIG_H */
